// This file is generated by Prismic local builder. Update with care!

export { default as BannerSlice } from './BannerSlice'
export { default as ContactSlice } from './ContactSlice'
export { default as CourseCurriculumSlice } from './CourseCurriculumSlice'
export { default as CourseHeaderSlice } from './CourseHeaderSlice'
export { default as CourseMenu } from './CourseMenu'
export { default as DirectorTeamSlice } from './DirectorTeamSlice'
export { default as HeaderSlice } from './HeaderSlice'
export { default as OurTeamSlice } from './OurTeamSlice'
export { default as QuoteSlice } from './QuoteSlice'
export { default as ServicesSlice } from './ServicesSlice'
export { default as TextSlice } from './TextSlice'
